export const mentors = [
  {
    id: 1,
    name: "Aziza K.",
    slug: "aziza-k",
    role: "CS Student",
    company: "MIT",
    flag: "\u{1F1FA}\u{1F1F8}",
    rating: 4.9,
    price: 8,
    sessions: 127,
    image: "https://i.pravatar.cc/300?img=5",
    bio: "Computer Science sophomore at MIT. Passionate about AI and helping students from Uzbekistan navigate the US college application process.",
    languages: ["English", "Uzbek", "Russian"],
    expertise: ["University Admissions", "CS Career", "Scholarships"],
    category: "University Admissions",
  },
  {
    id: 2,
    name: "Rustam T.",
    slug: "rustam-t",
    role: "Software Engineer",
    company: "Google",
    flag: "\u{1F1FA}\u{1F1F8}",
    rating: 4.8,
    price: 15,
    sessions: 203,
    image: "https://i.pravatar.cc/300?img=12",
    bio: "Senior Software Engineer at Google. Previously at startups in Tashkent. Happy to help with tech career preparation and interview prep.",
    languages: ["English", "Uzbek"],
    expertise: ["Interview Prep", "Career Guidance", "Software Engineering"],
    category: "Career Guidance",
  },
  {
    id: 3,
    name: "Nodira S.",
    slug: "nodira-s",
    role: "Medical Student",
    company: "UCL",
    flag: "\u{1F1EC}\u{1F1E7}",
    rating: 5.0,
    price: 10,
    sessions: 89,
    image: "https://i.pravatar.cc/300?img=9",
    bio: "3rd year Medical student at UCL. Specialized in guiding pre-med students through UCAS applications and BMAT preparation.",
    languages: ["English", "Uzbek", "Russian"],
    expertise: ["University Admissions", "Medicine", "UK Applications"],
    category: "University Admissions",
  },
  {
    id: 4,
    name: "Jamshid M.",
    slug: "jamshid-m",
    role: "Finance Analyst",
    company: "Deloitte",
    flag: "\u{1F1E6}\u{1F1EA}",
    rating: 4.7,
    price: 12,
    sessions: 156,
    image: "https://i.pravatar.cc/300?img=11",
    bio: "Finance Analyst at Deloitte Dubai. Graduated from Westminster International University in Tashkent. Expert in finance career paths.",
    languages: ["English", "Uzbek", "Russian"],
    expertise: ["Career Guidance", "Finance", "Interview Prep"],
    category: "Interview Prep",
  },
  {
    id: 5,
    name: "Malika R.",
    slug: "malika-r",
    role: "PhD Researcher",
    company: "KAIST",
    flag: "\u{1F1F0}\u{1F1F7}",
    rating: 4.9,
    price: 10,
    sessions: 74,
    image: "https://i.pravatar.cc/300?img=16",
    bio: "PhD researcher in AI at KAIST, South Korea. Full scholarship recipient. Helping students apply for graduate programs and scholarships in Asia.",
    languages: ["English", "Uzbek"],
    expertise: ["Graduate School", "Scholarships", "Research"],
    category: "University Admissions",
  },
  {
    id: 6,
    name: "Bobur A.",
    slug: "bobur-a",
    role: "Data Scientist",
    company: "Yandex",
    flag: "\u{1F1F7}\u{1F1FA}",
    rating: 4.6,
    price: 7,
    sessions: 98,
    image: "https://i.pravatar.cc/300?img=53",
    bio: "Data Scientist at Yandex Moscow. Self-taught programmer turned data expert. Helping career switchers enter tech.",
    languages: ["Russian", "Uzbek", "English"],
    expertise: ["Data Science", "Career Switch", "Skill Development"],
    category: "Skill Development",
  },
  {
    id: 7,
    name: "Dilnoza F.",
    slug: "dilnoza-f",
    role: "Product Manager",
    company: "Samsung",
    flag: "\u{1F1F0}\u{1F1F7}",
    rating: 4.8,
    price: 11,
    sessions: 112,
    image: "https://i.pravatar.cc/300?img=25",
    bio: "Product Manager at Samsung Seoul. Yonsei University graduate. Expert in Korean university applications and tech PM career paths.",
    languages: ["English", "Uzbek", "Korean"],
    expertise: ["Career Guidance", "Product Management", "Korea"],
    category: "Career Guidance",
  },
  {
    id: 8,
    name: "Sardor K.",
    slug: "sardor-k",
    role: "ML Engineer",
    company: "Microsoft",
    flag: "\u{1F1FA}\u{1F1F8}",
    rating: 4.7,
    price: 14,
    sessions: 167,
    image: "https://i.pravatar.cc/300?img=52",
    bio: "Machine Learning Engineer at Microsoft. Stanford MS graduate. Focused on helping students prepare for top US graduate programs.",
    languages: ["English", "Uzbek"],
    expertise: ["Graduate School", "Machine Learning", "Interview Prep"],
    category: "Interview Prep",
  },
  {
    id: 9,
    name: "Gulnora V.",
    slug: "gulnora-v",
    role: "UX Designer",
    company: "Spotify",
    flag: "\u{1F1F8}\u{1F1EA}",
    rating: 4.9,
    price: 9,
    sessions: 63,
    image: "https://i.pravatar.cc/300?img=32",
    bio: "Senior UX Designer at Spotify Stockholm. Helping aspiring designers build portfolios and break into the European tech scene.",
    languages: ["English", "Russian"],
    expertise: ["Design Career", "Portfolio Review", "Europe"],
    category: "Skill Development",
  },
  {
    id: 10,
    name: "Otabek N.",
    slug: "otabek-n",
    role: "Consultant",
    company: "McKinsey",
    flag: "\u{1F1EC}\u{1F1E7}",
    rating: 5.0,
    price: 20,
    sessions: 201,
    image: "https://i.pravatar.cc/300?img=60",
    bio: "Management Consultant at McKinsey London. Oxford MBA. Specialized in case interview prep and consulting career coaching.",
    languages: ["English", "Uzbek", "Russian"],
    expertise: ["Consulting", "Interview Prep", "MBA"],
    category: "Interview Prep",
  },
  {
    id: 11,
    name: "Shahlo M.",
    slug: "shahlo-m",
    role: "Civil Engineer",
    company: "Inha University",
    flag: "\u{1F1FA}\u{1F1FF}",
    rating: 4.5,
    price: 5,
    sessions: 45,
    image: "https://i.pravatar.cc/300?img=44",
    bio: "Civil Engineering student at Inha University Tashkent. Full scholarship holder. Helping high school students with local university admissions.",
    languages: ["Uzbek", "Russian", "English"],
    expertise: ["University Admissions", "Engineering", "Scholarships"],
    category: "University Admissions",
  },
  {
    id: 12,
    name: "Farhod J.",
    slug: "farhod-j",
    role: "Startup Founder",
    company: "TechStartup",
    flag: "\u{1F1FA}\u{1F1FF}",
    rating: 4.8,
    price: 13,
    sessions: 88,
    image: "https://i.pravatar.cc/300?img=68",
    bio: "Founded two tech startups in Tashkent. Y Combinator alum. Mentoring aspiring entrepreneurs and career switchers entering the startup world.",
    languages: ["Uzbek", "English", "Russian"],
    expertise: ["Entrepreneurship", "Career Switch", "Startups"],
    category: "Career Guidance",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Kamola A.",
    image: "https://i.pravatar.cc/300?img=20",
    quote:
      "Thanks to my mentor on Futurly, I got into UCL with a full scholarship! She reviewed my personal statement 4 times and each revision made it stronger.",
    achievement: "Accepted to UCL with full scholarship",
  },
  {
    id: 2,
    name: "Jasur D.",
    image: "https://i.pravatar.cc/300?img=51",
    quote:
      "I was stuck in a dead-end job and didn't know how to break into tech. My Futurly mentor helped me build a portfolio and prepare for interviews. Now I'm at Google!",
    achievement: "Landed Software Engineer role at Google",
  },
  {
    id: 3,
    name: "Madina R.",
    image: "https://i.pravatar.cc/300?img=24",
    quote:
      "The mock interview sessions were game-changing. My mentor knew exactly what Deloitte looks for and helped me practice until I was confident. Got the offer!",
    achievement: "Hired as Analyst at Deloitte",
  },
];

export const universities = [
  "MIT",
  "Stanford",
  "UCL",
  "Oxford",
  "KAIST",
  "Yonsei",
  "Moscow State",
  "Inha University Tashkent",
  "Westminster Intl. Uni. Tashkent",
  "Google",
  "Microsoft",
  "Deloitte",
  "Samsung",
  "Yandex",
];

export const teamMembers = [
  {
    name: "Divyansh M.",
    role: "Founder & CEO",
    image: "https://i.pravatar.cc/300?img=33",
    bio: "Former management consultant. Passionate about democratizing access to mentorship in Central Asia.",
  },
  {
    name: "Akbar S.",
    role: "CTO",
    image: "https://i.pravatar.cc/300?img=14",
    bio: "Full-stack engineer with experience at top tech companies. Building the platform that connects mentors and mentees.",
  },
  {
    name: "Zarina K.",
    role: "Head of Mentors",
    image: "https://i.pravatar.cc/300?img=23",
    bio: "Recruiter turned mentor advocate. Ensures quality and vets every mentor on the platform.",
  },
  {
    name: "Timur R.",
    role: "Head of Growth",
    image: "https://i.pravatar.cc/300?img=58",
    bio: "Growth marketing expert. Previously scaled edtech startups across CIS markets.",
  },
];

export const pricingPlans = [
  {
    name: "Free",
    price: "0",
    currency: "UZS",
    period: "month",
    description: "Get started with basic access",
    features: [
      "Browse mentors",
      "1 free intro session/month",
      "Community access",
      "University reviews",
    ],
    cta: "Get Started",
    popular: false,
  },
  {
    name: "Student Pro",
    price: "49,000",
    currency: "UZS",
    period: "month",
    usdEquiv: "~$4",
    description: "Everything you need for your journey",
    features: [
      "Everything in Free",
      "Unlimited messaging",
      "Priority booking",
      "SOP/Essay review (2/month)",
      "Group sessions",
      "Progress dashboard",
    ],
    cta: "Start Free Trial",
    popular: true,
  },
  {
    name: "Career Plus",
    price: "149,000",
    currency: "UZS",
    period: "month",
    usdEquiv: "~$12",
    description: "For serious career advancement",
    features: [
      "Everything in Pro",
      "Unlimited document reviews",
      "Mock interviews (4/month)",
      "Career path AI explorer",
      "Dedicated mentor matching",
      "Priority support",
    ],
    cta: "Start Free Trial",
    popular: false,
  },
];

export const faqItems = [
  {
    question: "Can I switch plans anytime?",
    answer:
      "Yes! You can upgrade, downgrade, or cancel your plan at any time. Changes take effect at the start of your next billing cycle.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept Payme, Click, Uzum, Visa, and Mastercard. All payments are processed securely through our payment partners.",
  },
  {
    question: "Is there a refund policy?",
    answer:
      "Yes, we offer a full refund within 7 days of your subscription if you're not satisfied. Individual session refunds are handled on a case-by-case basis.",
  },
  {
    question: "Do mentors set their own prices?",
    answer:
      "Yes, mentors set their own session rates. The subscription plans give you platform features, while session fees go directly to your mentor.",
  },
  {
    question: "Can I use Futurly for free?",
    answer:
      "Absolutely! Our Free plan lets you browse mentors, read university reviews, and get one free intro session per month. It's a great way to get started.",
  },
];
